runtime: nodejs12

instance_class: F1

entrypoint: "node build/index.js"

env_variables:
  ON_GAE: true
  GCS_CLOUD_BUCKET: $GCS_CLOUD_BUCKET
  GCSQL_DB_USER: $GCSQL_DB_USER
  GCSQL_DB_PASS: $GCSQL_DB_PASS
  GCSQL_DB_NAME: $GCSQL_DB_NAME
  GCSQL_CONNECTION_NAME: $GCSQL_CONNECTION_NAME
  GCSQL_DB_SOCKET_PATH: /cloudsql
  