name: Deploy to heroku

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        # Sets working directory to be in repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Deploy to production
        run: |
          git push https://heroku:${{ secrets.HEROKU_API_KEY }}@git.heroku.com/dk-api-21.git main
        